name: publish

on:
  push:
    branches: [main, dev]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: GHCR Login
      uses: khlam/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and publish
      run: |
        docker build . --squash --tag ghcr.io/${{ github.repository }}/pyt:latest
        docker run ghcr.io/${{ github.repository }}/pyt:latest
        docker push ghcr.io/${{ github.repository }}/pyt:latest